// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    var bottomPaginatorView, paginator, topPaginatorView;
    paginator = new Compaginator.Model();
    paginator.setNumPages(20);
    paginator.observe('page-changed', function() {
      topPaginatorView.render(paginator, '.pagination-top');
      return bottomPaginatorView.render(paginator, '.pagination-bottom');
    });
    topPaginatorView = new Compaginator.JqueryView(paginator, '.pagination-top');
    return bottomPaginatorView = new Compaginator.JqueryView(paginator, '.pagination-bottom');
  });

}).call(this);
